In [19]:
import pandas as pd
pd.DataFrame(pd.read_json('./problemset.problems.json.gz').result)

                                                              result
problemStatistics  [{'contestId': 1919, 'index': 'H', 'solvedCoun...
problems           [{'contestId': 1919, 'index': 'H', 'name': 'Tr...

In [21]:
pd.DataFrame(pd.read_json('./problemset.problems.json.gz').result.problems)

,contestId,index,name,type,points,rating,tags
0,1919,H,Tree Diameter,PROGRAMMING,5000.0,3500.0,"[interactive, trees]"
1,1919,G,Tree LGM,PROGRAMMING,4000.0,3500.0,"[constructive algorithms, games, trees]"
2,1919,F2,Wine Factory (Hard Version),PROGRAMMING,1500.0,2800.0,"[data structures, dp, flows, matrices]"
3,1919,F1,Wine Factory (Easy Version),PROGRAMMING,1500.0,2300.0,"[data structures, greedy]"
4,1919,E,Counting Prefixes,PROGRAMMING,2250.0,2600.0,"[combinatorics, dp, geometry, math]"
...,...,...,...,...,...,...,...
9200,2,B,The least round way,PROGRAMMING,NaN,2000.0,"[dp, math]"
9201,2,A,Winner,PROGRAMMING,NaN,1500.0,"[hashing, implementation]"
9202,1,C,Ancient Berland Circus,PROGRAMMING,NaN,2100.0,"[geometry, math]"
9203,1,B,Spreadsheet,PROGRAMMING,NaN,1600.0,"[implementation, math]"
9204,1,A,Theatre Square,PROGRAMMING,NaN,1000.0,[math]

In [20]:
pd.DataFrame(pd.read_json('./problemset.problems.json.gz').result.problemStatistics)

      contestId index  solvedCount
0          1919     H           31
1          1919     G           35
2          1919    F2          348
3          1919    F1         1204
4          1919     E          377
...         ...   ...          ...
9200          2     B         9787
9201          2     A        23539
9202          1     C         5203
9203          1     B        20830
9204          1     A       233547

[9205 rows x 3 columns]